// This file is auto-generated, please do not modify manually
using System;
using CuberiteClr.Sdk.Types;

namespace CuberiteClr.Runtime.Interop;

public static unsafe class WrapperFunctions
{
	public static delegate* unmanaged[Cdecl]<string, void> log_default;
	public static delegate* unmanaged[Cdecl]<string, void> log_info;
	public static delegate* unmanaged[Cdecl]<string, void> log_warning;
	public static delegate* unmanaged[Cdecl]<string, void> log_error;
	public static delegate* unmanaged[Cdecl]<string, void> log_debug;
	public static delegate* unmanaged[Cdecl]<string, IntPtr, string, string, bool> bind_command;
	public static delegate* unmanaged[Cdecl]<short, IntPtr> item_type_to_string;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> enchantments_to_string;
	public static delegate* unmanaged[Cdecl]<IntPtr, float> entity_get_health;
	public static delegate* unmanaged[Cdecl]<IntPtr, float, void> entity_set_health;
	public static delegate* unmanaged[Cdecl]<IntPtr, bool> entity_is_invisible;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> entity_get_world;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr, void> entity_take_damage_1;
	public static delegate* unmanaged[Cdecl]<IntPtr, DamageType, IntPtr, int, double, void> entity_take_damage_2;
	public static delegate* unmanaged[Cdecl]<IntPtr, DamageType, int, int, double, void> entity_take_damage_3;
	public static delegate* unmanaged[Cdecl]<IntPtr, DamageType, IntPtr, int, float, double, void> entity_take_damage_4;
	public static delegate* unmanaged[Cdecl]<IntPtr, int, void> entity_heal;
	public static delegate* unmanaged[Cdecl]<IntPtr, EntityType> entity_get_entity_type;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> entity_get_position;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> entity_get_class;
	public static delegate* unmanaged[Cdecl]<IntPtr, string, bool> entity_is_a;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> entity_get_parent_class;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr, byte> inventory_add_item;
	public static delegate* unmanaged[Cdecl]<IntPtr, short> item_get_type;
	public static delegate* unmanaged[Cdecl]<IntPtr, byte> item_get_count;
	public static delegate* unmanaged[Cdecl]<IntPtr, short> item_get_damage;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> item_get_custom_name;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> item_get_enchantments;
	public static delegate* unmanaged[Cdecl]<IntPtr, bool> pickup_is_player_created;
	public static delegate* unmanaged[Cdecl]<IntPtr, bool> pickup_is_collected;
	public static delegate* unmanaged[Cdecl]<IntPtr, bool> pickup_can_combine;
	public static delegate* unmanaged[Cdecl]<IntPtr, bool, void> pickup_set_can_combine;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr, bool> pickup_collected_by;
	public static delegate* unmanaged[Cdecl]<IntPtr, int> pickup_get_age;
	public static delegate* unmanaged[Cdecl]<IntPtr, int, void> pickup_set_age;
	public static delegate* unmanaged[Cdecl]<IntPtr, int> pickup_get_lifetime;
	public static delegate* unmanaged[Cdecl]<IntPtr, int, void> pickup_set_lifetime;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> pickup_get_item;
	public static delegate* unmanaged[Cdecl]<IntPtr, GameMode> player_get_game_mode;
	public static delegate* unmanaged[Cdecl]<IntPtr, GameMode, void> player_set_game_mode;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> player_get_inventory;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> player_get_name;
	public static delegate* unmanaged[Cdecl]<IntPtr, bool, void> player_set_visible;
	public static delegate* unmanaged[Cdecl]<IntPtr, Guid> player_get_uuid;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> player_get_client_handle;
	public static delegate* unmanaged[Cdecl]<IntPtr, string, void> player_send_message;
	public static delegate* unmanaged[Cdecl]<IntPtr, int, double, bool> player_feed;
	public static delegate* unmanaged[Cdecl]<IntPtr, Vector3i, IntPtr, void> player_set_respawn_location;
	public static delegate* unmanaged[Cdecl]<string, MessageType, void> root_broadcast_chat;
	public static delegate* unmanaged[Cdecl]<IntPtr> root_get_default_world;
	public static delegate* unmanaged[Cdecl]<IntPtr, bool> root_for_each_world;
	public static delegate* unmanaged[Cdecl]<IntPtr, bool> root_for_each_player;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> client_handle_get_player;
	public static delegate* unmanaged[Cdecl]<IntPtr, bool> world_are_command_blocks_enabled;
	public static delegate* unmanaged[Cdecl]<IntPtr, bool, void> world_set_command_blocks_enabled;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr> world_get_name;
	public static delegate* unmanaged[Cdecl]<IntPtr, Vector3i, BlockType> world_get_block;
	public static delegate* unmanaged[Cdecl]<IntPtr, Vector3i, BlockType, byte, void> world_set_block;
	public static delegate* unmanaged[Cdecl]<IntPtr, string, IntPtr, MessageType, void> world_broadcast_chat;
	public static delegate* unmanaged[Cdecl]<IntPtr, Vector3i, IntPtr, void> world_dig_block;
	public static delegate* unmanaged[Cdecl]<IntPtr, double, Vector3d, bool, ExplosionSource, IntPtr, void> world_do_explosion_at;
	public static delegate* unmanaged[Cdecl]<IntPtr, GameMode> world_get_game_mode;
	public static delegate* unmanaged[Cdecl]<IntPtr, Weather> world_get_weather;
	public static delegate* unmanaged[Cdecl]<IntPtr, Weather, void> world_set_weather;
	public static delegate* unmanaged[Cdecl]<IntPtr, int> world_get_time_of_day;
	public static delegate* unmanaged[Cdecl]<IntPtr, int, void> world_set_time_of_day;
	public static delegate* unmanaged[Cdecl]<IntPtr, long> world_get_world_age;
	public static delegate* unmanaged[Cdecl]<IntPtr, long> world_get_world_tick_age;
	public static delegate* unmanaged[Cdecl]<IntPtr, long> world_get_world_date;
	public static delegate* unmanaged[Cdecl]<IntPtr, IntPtr, bool> world_for_each_player;
	public static delegate* unmanaged[Cdecl]<short, byte, short, string, string, IntPtr, int, IntPtr> create_item;
	public static delegate* unmanaged[Cdecl]<IntPtr, void> delete_item;
	public static delegate* unmanaged[Cdecl]<Vector3d, IntPtr, bool, Vector3f, int, bool, IntPtr> create_pickup;
	public static delegate* unmanaged[Cdecl]<IntPtr, void> delete_pickup;


	public static void Initialize(IntPtr* ptr)
	{
		log_default = (delegate* unmanaged[Cdecl]<string, void>) *(ptr + 0);
		log_info = (delegate* unmanaged[Cdecl]<string, void>) *(ptr + 1);
		log_warning = (delegate* unmanaged[Cdecl]<string, void>) *(ptr + 2);
		log_error = (delegate* unmanaged[Cdecl]<string, void>) *(ptr + 3);
		log_debug = (delegate* unmanaged[Cdecl]<string, void>) *(ptr + 4);
		bind_command = (delegate* unmanaged[Cdecl]<string, IntPtr, string, string, bool>) *(ptr + 5);
		item_type_to_string = (delegate* unmanaged[Cdecl]<short, IntPtr>) *(ptr + 6);
		enchantments_to_string = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 7);
		entity_get_health = (delegate* unmanaged[Cdecl]<IntPtr, float>) *(ptr + 8);
		entity_set_health = (delegate* unmanaged[Cdecl]<IntPtr, float, void>) *(ptr + 9);
		entity_is_invisible = (delegate* unmanaged[Cdecl]<IntPtr, bool>) *(ptr + 10);
		entity_get_world = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 11);
		entity_take_damage_1 = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr, void>) *(ptr + 12);
		entity_take_damage_2 = (delegate* unmanaged[Cdecl]<IntPtr, DamageType, IntPtr, int, double, void>) *(ptr + 13);
		entity_take_damage_3 = (delegate* unmanaged[Cdecl]<IntPtr, DamageType, int, int, double, void>) *(ptr + 14);
		entity_take_damage_4 = (delegate* unmanaged[Cdecl]<IntPtr, DamageType, IntPtr, int, float, double, void>) *(ptr + 15);
		entity_heal = (delegate* unmanaged[Cdecl]<IntPtr, int, void>) *(ptr + 16);
		entity_get_entity_type = (delegate* unmanaged[Cdecl]<IntPtr, EntityType>) *(ptr + 17);
		entity_get_position = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 18);
		entity_get_class = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 19);
		entity_is_a = (delegate* unmanaged[Cdecl]<IntPtr, string, bool>) *(ptr + 20);
		entity_get_parent_class = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 21);
		inventory_add_item = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr, byte>) *(ptr + 22);
		item_get_type = (delegate* unmanaged[Cdecl]<IntPtr, short>) *(ptr + 23);
		item_get_count = (delegate* unmanaged[Cdecl]<IntPtr, byte>) *(ptr + 24);
		item_get_damage = (delegate* unmanaged[Cdecl]<IntPtr, short>) *(ptr + 25);
		item_get_custom_name = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 26);
		item_get_enchantments = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 27);
		pickup_is_player_created = (delegate* unmanaged[Cdecl]<IntPtr, bool>) *(ptr + 28);
		pickup_is_collected = (delegate* unmanaged[Cdecl]<IntPtr, bool>) *(ptr + 29);
		pickup_can_combine = (delegate* unmanaged[Cdecl]<IntPtr, bool>) *(ptr + 30);
		pickup_set_can_combine = (delegate* unmanaged[Cdecl]<IntPtr, bool, void>) *(ptr + 31);
		pickup_collected_by = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr, bool>) *(ptr + 32);
		pickup_get_age = (delegate* unmanaged[Cdecl]<IntPtr, int>) *(ptr + 33);
		pickup_set_age = (delegate* unmanaged[Cdecl]<IntPtr, int, void>) *(ptr + 34);
		pickup_get_lifetime = (delegate* unmanaged[Cdecl]<IntPtr, int>) *(ptr + 35);
		pickup_set_lifetime = (delegate* unmanaged[Cdecl]<IntPtr, int, void>) *(ptr + 36);
		pickup_get_item = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 37);
		player_get_game_mode = (delegate* unmanaged[Cdecl]<IntPtr, GameMode>) *(ptr + 38);
		player_set_game_mode = (delegate* unmanaged[Cdecl]<IntPtr, GameMode, void>) *(ptr + 39);
		player_get_inventory = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 40);
		player_get_name = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 41);
		player_set_visible = (delegate* unmanaged[Cdecl]<IntPtr, bool, void>) *(ptr + 42);
		player_get_uuid = (delegate* unmanaged[Cdecl]<IntPtr, Guid>) *(ptr + 43);
		player_get_client_handle = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 44);
		player_send_message = (delegate* unmanaged[Cdecl]<IntPtr, string, void>) *(ptr + 45);
		player_feed = (delegate* unmanaged[Cdecl]<IntPtr, int, double, bool>) *(ptr + 46);
		player_set_respawn_location = (delegate* unmanaged[Cdecl]<IntPtr, Vector3i, IntPtr, void>) *(ptr + 47);
		root_broadcast_chat = (delegate* unmanaged[Cdecl]<string, MessageType, void>) *(ptr + 48);
		root_get_default_world = (delegate* unmanaged[Cdecl]<IntPtr>) *(ptr + 49);
		root_for_each_world = (delegate* unmanaged[Cdecl]<IntPtr, bool>) *(ptr + 50);
		root_for_each_player = (delegate* unmanaged[Cdecl]<IntPtr, bool>) *(ptr + 51);
		client_handle_get_player = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 52);
		world_are_command_blocks_enabled = (delegate* unmanaged[Cdecl]<IntPtr, bool>) *(ptr + 53);
		world_set_command_blocks_enabled = (delegate* unmanaged[Cdecl]<IntPtr, bool, void>) *(ptr + 54);
		world_get_name = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr>) *(ptr + 55);
		world_get_block = (delegate* unmanaged[Cdecl]<IntPtr, Vector3i, BlockType>) *(ptr + 56);
		world_set_block = (delegate* unmanaged[Cdecl]<IntPtr, Vector3i, BlockType, byte, void>) *(ptr + 57);
		world_broadcast_chat = (delegate* unmanaged[Cdecl]<IntPtr, string, IntPtr, MessageType, void>) *(ptr + 58);
		world_dig_block = (delegate* unmanaged[Cdecl]<IntPtr, Vector3i, IntPtr, void>) *(ptr + 59);
		world_do_explosion_at = (delegate* unmanaged[Cdecl]<IntPtr, double, Vector3d, bool, ExplosionSource, IntPtr, void>) *(ptr + 60);
		world_get_game_mode = (delegate* unmanaged[Cdecl]<IntPtr, GameMode>) *(ptr + 61);
		world_get_weather = (delegate* unmanaged[Cdecl]<IntPtr, Weather>) *(ptr + 62);
		world_set_weather = (delegate* unmanaged[Cdecl]<IntPtr, Weather, void>) *(ptr + 63);
		world_get_time_of_day = (delegate* unmanaged[Cdecl]<IntPtr, int>) *(ptr + 64);
		world_set_time_of_day = (delegate* unmanaged[Cdecl]<IntPtr, int, void>) *(ptr + 65);
		world_get_world_age = (delegate* unmanaged[Cdecl]<IntPtr, long>) *(ptr + 66);
		world_get_world_tick_age = (delegate* unmanaged[Cdecl]<IntPtr, long>) *(ptr + 67);
		world_get_world_date = (delegate* unmanaged[Cdecl]<IntPtr, long>) *(ptr + 68);
		world_for_each_player = (delegate* unmanaged[Cdecl]<IntPtr, IntPtr, bool>) *(ptr + 69);
		create_item = (delegate* unmanaged[Cdecl]<short, byte, short, string, string, IntPtr, int, IntPtr>) *(ptr + 70);
		delete_item = (delegate* unmanaged[Cdecl]<IntPtr, void>) *(ptr + 71);
		create_pickup = (delegate* unmanaged[Cdecl]<Vector3d, IntPtr, bool, Vector3f, int, bool, IntPtr>) *(ptr + 72);
		delete_pickup = (delegate* unmanaged[Cdecl]<IntPtr, void>) *(ptr + 73);

	}
}
